name: Deploy to Cloudsplitter
on: 
  push:
    branches: [ master ]

jobs:
  Deploy-To-Cloudsplitter:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - name: Copy config.ts
        run: cp ~/configs/frontend-config.ts ${{ github.workspace }}/src/config.ts
      - name: Installing dependencies
        run: yarn install
      - name: Building the project
        run: yarn build
      - name: Copying files to server
        run: cp -r ${{ github.workspace }}/build ~/deployment/paperhub-backend/
